### ISSUE TITLE
PHP8.0 deprecation notices / update Redux

### ISSUE THREAD

**Issue by Spreeuw** [kgjerstad/wp-mail-logging#122]
See: https://wordpress.org/support/topic/php-8-0-compatibility-6/

> Are you planing on adding PHP8.0 compatibility. We are getting several errors coming from your plugin:
> 
> ```
> Deprecated: Required parameter $handle follows optional parameter $register in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_cdn.php on line 104
> 
> Deprecated: Required parameter $src_cdn follows optional parameter $register in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_cdn.php on line 104
> 
> Deprecated: Required parameter $deps follows optional parameter $register in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_cdn.php on line 104
> 
> Deprecated: Required parameter $ver follows optional parameter $register in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_cdn.php on line 104
> 
> Deprecated: Required parameter $footer_or_media follows optional parameter $register in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/class.redux_cdn.php on line 104
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/fields/switch/field_switch.php on line 17
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/fields/select/field_select.php on line 17
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/fields/section/field_section.php on line 43
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/fields/slider/field_slider.php on line 40
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/extensions/options_object/options_object/field_options_object.php on line 42
> 
> Deprecated: Required parameter $parent follows optional parameter $field in /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/extensions/import_export/import_export/field_import_export.php on line 42
> ```

And:

>  It seems you are using a very old version of the Redux framework in this plugin (v3.6.12 = Sep 17, 2018), this was fixed in the new Redux 4.0 recently: https://github.com/reduxframework/redux-framework-4/pull/199

**Comment by stgoos** [comment]
Good to see that there is already a ticket open for this topic. I think that the list of affected files is even longer as I also had files like 

> /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/framework.php
> /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/fields/ace_editor/fields_ace_editor.php
> /wp-content/plugins/wp-mail-logging/lib/vendor/redux-framework/inc/extensions/customizer/extension_customizer.php

to fix.

I just manually fixed the files of the embeded Redux Framework version by adding = '' after the required parameters to stop the message flood my log files so I can do an actual deepdive into a problem I have with a plugin I'm writting :)

**Comment by Spreeuw** [comment]
Closed by 1382ce51640956aa98a2f3f66dcc4f6c99a7a485
